TOPDIR ?= ../..
include $(TOPDIR)/.config

$(HEATING_CTRL_SUPPORT)_SRC += services/heating_controller/heating_ctrl.c
$(HEATING_CTRL_SUPPORT)_ECMD_SRC += services/heating_controller/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
